function EZ = EZ_m1_s0_3_5(dt,Dm0,Dm1,Ds0)
%EZ_M1_S0_3_5
%    EZ = EZ_M1_S0_3_5(DT,DM0,DM1,DS0)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-May-2023 14:53:32

%E(Z) function of refined Hermite, J=3  K=5 ndiff_mu = 1, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm0.^3;
t4 = Dm1.^2;
t5 = Dm1.^3;
t7 = Ds0.^2;
t8 = dt.^2;
t9 = dt.^3;
t11 = sqrt(dt);
t6 = t4.^2;
t10 = t8.^2;
t12 = t11.^3;
t13 = t11.^5;
t14 = t11.^7;
EZ = [(Dm0.*t11.*1.2e+2+Dm0.*Dm1.*t12.*6.0e+1+Dm0.*t4.*t13.*2.0e+1+Dm0.*t5.*t14.*5.0+Dm0.*t6.*t12.^3)./(Ds0.*1.2e+2);(t7.*(Dm1.*dt.*6.0e+1+t4.*t8.*4.0e+1+t5.*t9.*2.0e+1+t6.*t10.*8.0+6.0e+1)+dt.*t2.*6.0e+1+Dm1.*t2.*t8.*6.0e+1+t2.*t4.*t9.*3.5e+1+t2.*t5.*t10.*1.5e+1)./(t7.*6.0e+1);(1.0./Ds0.^3.*(t3.*t12.*8.0+t7.*(Dm0.*t11.*2.4e+1+Dm0.*Dm1.*t12.*3.6e+1+Dm0.*t4.*t13.*3.2e+1+Dm0.*t5.*t14.*2.1e+1)+Dm1.*t3.*t13.*1.2e+1+t3.*t4.*t14.*1.0e+1))./8.0];
