function EZ = EZ_m1_s0_3_7(dt,Dm0,Dm1,Ds0)
%EZ_m1_s0_3_7
%    EZ = EZ_m1_s0_3_7(DT,Dm0,Dm1,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Mar-2024 12:58:12

%E(Z) function of refined Hermite, J=3  K=7 ndiff_mu = 1, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm0.^3;
t4 = Dm1.^2;
t5 = Dm1.^3;
t7 = Dm1.^5;
t9 = Ds0.^2;
t10 = dt.^2;
t11 = dt.^3;
t13 = dt.^5;
t15 = sqrt(dt);
t6 = t4.^2;
t8 = t4.^3;
t12 = t10.^2;
t14 = t10.^3;
t16 = t15.^3;
t17 = t15.^5;
t18 = t15.^7;
t20 = t15.^11;
t19 = t16.^3;
mt1 = [(Dm0.*t15.*5.04e+3+Dm0.*Dm1.*t16.*2.52e+3+Dm0.*t4.*t17.*8.4e+2+Dm0.*t5.*t18.*2.1e+2+Dm0.*t6.*t19.*4.2e+1+Dm0.*t7.*t20.*7.0+Dm0.*t8.*t15.^13)./(Ds0.*5.04e+3);(dt.*t2.*2.52e+3+t9.*(Dm1.*dt.*2.52e+3+t4.*t10.*1.68e+3+t5.*t11.*8.4e+2+t6.*t12.*3.36e+2+t7.*t13.*1.12e+2+t8.*t14.*3.2e+1+2.52e+3)+Dm1.*t2.*t10.*2.52e+3+t2.*t4.*t11.*1.47e+3+t2.*t5.*t12.*6.3e+2+t2.*t6.*t13.*2.17e+2+t2.*t7.*t14.*6.3e+1)./(t9.*2.52e+3)];
mt2 = [(1.0./Ds0.^3.*(t3.*t16.*2.4e+2+t9.*(Dm0.*t15.*7.2e+2+Dm0.*Dm1.*t16.*1.08e+3+Dm0.*t4.*t17.*9.6e+2+Dm0.*t5.*t18.*6.3e+2+Dm0.*t6.*t19.*3.32e+2+Dm0.*t7.*t20.*1.47e+2)+Dm1.*t3.*t17.*3.6e+2+t3.*t4.*t18.*3.0e+2+t3.*t5.*t19.*1.8e+2+t3.*t6.*t20.*8.6e+1))./2.4e+2];
EZ = [mt1;mt2];
end
