function EZ = EZ_m1_s0_3_4(dt,Dm0,Dm1,Ds0)
%EZ_m1_s0_3_4
%    EZ = EZ_m1_s0_3_4(DT,Dm0,Dm1,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Mar-2024 12:52:53

%E(Z) function of refined Hermite, J=3  K=4 ndiff_mu = 1, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm0.^3;
t4 = Dm1.^2;
t5 = Dm1.^3;
t6 = Ds0.^2;
t7 = dt.^2;
t8 = dt.^3;
t9 = sqrt(dt);
t10 = t9.^3;
t11 = t9.^5;
EZ = [(Dm0.*t9.*2.4e+1+Dm0.*Dm1.*t10.*1.2e+1+Dm0.*t4.*t11.*4.0+Dm0.*t5.*t9.^7)./(Ds0.*2.4e+1);(dt.*t2.*1.2e+1+t6.*(Dm1.*dt.*1.2e+1+t4.*t7.*8.0+t5.*t8.*4.0+1.2e+1)+Dm1.*t2.*t7.*1.2e+1+t2.*t4.*t8.*7.0)./(t6.*1.2e+1);(1.0./Ds0.^3.*(t6.*(Dm0.*t9.*6.0+Dm0.*Dm1.*t10.*9.0+Dm0.*t4.*t11.*8.0)+t3.*t10.*2.0+Dm1.*t3.*t11.*3.0))./2.0];
end
