function EZ = EZ_m3_s0_3_4(dt,Dm0,Dm1,Dm2,Dm3,Ds0)
%EZ_M3_S0_3_4
%    EZ = EZ_M3_S0_3_4(DT,DM0,DM1,DM2,DM3,DS0)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-May-2023 09:13:14

%E(Z) function of refined Hermite, J=3  K=4 ndiff_mu = 3, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm0.^3;
t4 = Dm1.^2;
t5 = Dm1.^3;
t6 = Dm2.^2;
t7 = Ds0.^2;
t8 = dt.^2;
t9 = dt.^3;
t10 = sqrt(dt);
t11 = t10.^3;
t12 = t10.^5;
t13 = t10.^7;
t14 = Dm0.*t4.*t12.*1.6e+1;
EZ = [(t14+Dm0.*t10.*9.6e+1+t7.*(Dm2.*t11.*2.4e+1+Dm0.*Dm3.*t12.*1.6e+1+Dm1.*Dm2.*t12.*2.4e+1+Dm0.*t6.*t13.*1.4e+1+Dm2.*t4.*t13.*1.4e+1+Dm0.*Dm1.*Dm3.*t13.*2.2e+1+Dm2.*Dm3.*t7.*t13.*1.1e+1)+Dm0.*Dm1.*t11.*4.8e+1+Dm2.*t2.*t12.*1.6e+1+Dm0.*t5.*t13.*4.0+Dm3.*t3.*t13.*4.0+Dm1.*Dm2.*t2.*t13.*1.6e+1)./(Ds0.*9.6e+1);(dt.*t2.*4.8e+1+t7.*(Dm1.*dt.*4.8e+1+t4.*t8.*3.2e+1+t5.*t9.*1.6e+1+t7.*(Dm3.*t8.*1.6e+1+t6.*t9.*2.1e+1+Dm1.*Dm3.*t9.*3.2e+1)+Dm0.*Dm2.*t8.*5.6e+1+Dm3.*t2.*t9.*2.8e+1+Dm0.*Dm1.*Dm2.*t9.*8.8e+1+4.8e+1)+Dm1.*t2.*t8.*4.8e+1+Dm2.*t3.*t9.*1.6e+1+t2.*t4.*t9.*2.8e+1)./(t7.*4.8e+1);(1.0./Ds0.^3.*(t3.*t11.*4.0+t7.*(t14+t7.*(Dm2.*t11.*7.0+Dm0.*Dm3.*t12.*9.0+Dm1.*Dm2.*t12.*1.5e+1)+Dm0.*t10.*1.2e+1+Dm0.*Dm1.*t11.*1.8e+1+Dm2.*t2.*t12.*1.3e+1)+Dm1.*t3.*t12.*6.0))./4.0];
