function EZ = EZ_m1_s0_3_2(dt,Dm0,Dm1,Ds0)
%EZ_m1_s0_3_2
%    EZ = EZ_m1_s0_3_2(DT,Dm0,Dm1,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Mar-2024 12:51:40

%E(Z) function of refined Hermite, J=3  K=2 ndiff_mu = 1, ndiff_sigma = 0
t2 = 1.0./Ds0;
t3 = sqrt(dt);
EZ = [(t2.*(Dm0.*t3.*2.0+Dm0.*Dm1.*t3.^3))./2.0;t2.^2.*(Dm0.^2.*dt+1.0./t2.^2.*(Dm1.*dt+1.0));Dm0.*t2.*t3.*3.0];
end
