function EZ = EZ_m3_s0_1_6(dt,Dm0,Dm1,Dm2,Dm3,Ds0)
%EZ_M3_S0_1_6
%    EZ = EZ_M3_S0_1_6(DT,DM0,DM1,DM2,DM3,DS0)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2023 15:52:22

%E(Z) function of refined Hermite, J=1  K=6 ndiff_mu = 3, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm0.^3;
t4 = Dm1.^2;
t5 = Dm1.^3;
t6 = Dm2.^2;
t8 = Dm2.^3;
t9 = Dm3.^2;
t10 = Ds0.^2;
t11 = dt.^(3.0./2.0);
t12 = dt.^(5.0./2.0);
t13 = dt.^(7.0./2.0);
t15 = dt.^(1.1e+1./2.0);
t7 = t4.^2;
t14 = t11.^3;
EZ = (Dm0.*sqrt(dt).*5.76e+3+t10.*(Dm2.*t11.*1.44e+3+t10.*(t8.*t14.*2.52e+2+Dm2.*Dm3.*t13.*6.6e+2+Dm0.*t9.*t14.*4.32e+2+Dm1.*t8.*t15.*4.86e+2+Dm1.*Dm2.*Dm3.*t14.*1.236e+3+Dm0.*Dm3.*t6.*t15.*1.174e+3+Dm2.*Dm3.*t4.*t15.*1.268e+3+Dm0.*Dm1.*t9.*t15.*9.74e+2+Dm2.*t9.*t10.*t15.*4.71e+2)+Dm0.*Dm3.*t12.*9.6e+2+Dm1.*Dm2.*t12.*1.44e+3+Dm0.*t6.*t13.*8.4e+2+Dm2.*t4.*t13.*8.4e+2+Dm2.*t5.*t14.*3.6e+2+Dm2.*t7.*t15.*1.24e+2+t2.*t8.*t15.*3.4e+2+t3.*t9.*t15.*2.2e+2+Dm0.*Dm1.*Dm3.*t13.*1.32e+3+Dm0.*Dm1.*t6.*t14.*1.224e+3+Dm0.*Dm3.*t4.*t14.*1.032e+3+Dm2.*Dm3.*t2.*t14.*9.6e+2+Dm0.*Dm3.*t5.*t15.*5.92e+2+Dm0.*t4.*t6.*t15.*9.68e+2+Dm1.*Dm2.*Dm3.*t2.*t15.*1.78e+3)+Dm0.*Dm1.*t11.*2.88e+3+Dm0.*t4.*t12.*9.6e+2+Dm2.*t2.*t12.*9.6e+2+Dm0.*t5.*t13.*2.4e+2+Dm3.*t3.*t13.*2.4e+2+Dm0.*t7.*t14.*4.8e+1+t3.*t6.*t14.*1.92e+2+Dm0.*Dm1.^5.*t15.*8.0+Dm2.*Dm3.*t2.^2.*t15.*1.2e+2+Dm1.*Dm2.*t2.*t13.*9.6e+2+Dm1.*Dm3.*t3.*t14.*3.36e+2+Dm2.*t2.*t4.*t14.*5.28e+2+Dm2.*t2.*t5.*t15.*2.08e+2+Dm1.*t3.*t6.*t15.*2.72e+2+Dm3.*t3.*t4.*t15.*2.56e+2)./(Ds0.*5.76e+3);
