function EZ = EZ_m2_s2_3_1(dt,Dm0,Dm1,Dm2,Ds0,Ds1,Ds2)
%EZ_M2_S2_3_1
%    EZ = EZ_M2_S2_3_1(DT,DM0,DM1,DM2,DS0,DS1,DS2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2023 12:23:08

%E(Z) function of refined Hermite, J=3  K=1 ndiff_mu = 2, ndiff_sigma = 2
t2 = sqrt(dt);
t3 = Ds0./1.0e+100;
EZ = [(Dm0.*t2.*2.0-Ds0.*Ds1.*t2)./(Ds0.*2.0);t3+1.0;t3];
