function EZ = EZ_m3_s0_4_3(dt,Dm0,Dm1,Dm2,Dm3,Ds0)
%EZ_m3_s0_4_3
%    EZ = EZ_m3_s0_4_3(DT,Dm0,Dm1,Dm2,Dm3,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Jan-2024 14:49:34

%E(Z) function of refined Hermite, J=4  K=3 ndiff_mu = 3, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm1.^2;
t4 = Ds0.^2;
t5 = dt.^2;
t6 = Dm1.*dt.*6.0;
t8 = sqrt(dt);
t7 = 1.0./t4;
t9 = t8.^3;
t10 = t8.^5;
t11 = dt.*t2.*6.0;
EZ = [(t4.*(Dm2.*t9.*3.0+Dm0.*Dm3.*t10.*2.0+Dm1.*Dm2.*t10.*3.0)+Dm0.*t8.*1.2e+1+Dm0.*Dm1.*t9.*6.0+Dm0.*t3.*t10.*2.0+Dm2.*t2.*t10.*2.0)./(Ds0.*1.2e+1);(t7.*(t11+t4.*(t6+t3.*t5.*4.0+Dm0.*Dm2.*t5.*7.0+Dm3.*t4.*t5.*2.0+6.0)+Dm1.*t2.*t5.*6.0))./6.0;(1.0./Ds0.^3.*(Dm0.^3.*t9.*4.0+t4.*(t8.*(Dm0.*1.2e+1+Dm0.*Dm1.*dt.*1.8e+1)+Dm2.*t4.*t9.*7.0)))./4.0;t7.*(t11+t4.*(t6+3.0))];
end
