function EZ = EZ_m1_s0_3_3(dt,Dm0,Dm1,Ds0)
%EZ_m1_s0_3_3
%    EZ = EZ_m1_s0_3_3(DT,Dm0,Dm1,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Mar-2024 12:52:36

%E(Z) function of refined Hermite, J=3  K=3 ndiff_mu = 1, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm1.^2;
t4 = Ds0.^2;
t5 = dt.^2;
t6 = sqrt(dt);
t7 = t6.^3;
EZ = [(Dm0.*t6.*6.0+Dm0.*Dm1.*t7.*3.0+Dm0.*t3.*t6.^5)./(Ds0.*6.0);(dt.*t2.*3.0+t4.*(Dm1.*dt.*3.0+t3.*t5.*2.0+3.0)+Dm1.*t2.*t5.*3.0)./(t4.*3.0);(1.0./Ds0.^3.*(Dm0.^3.*t7.*2.0+t4.*t6.*(Dm0.*6.0+Dm0.*Dm1.*dt.*9.0)))./2.0];
end
