function EZ = EZ_m3_s3_3_2(dt,Dm0,Dm1,Dm2,Dm3,Ds0,Ds1,Ds2,Ds3)
%EZ_m3_s3_3_2
%    EZ = EZ_m3_s3_3_2(DT,Dm0,Dm1,Dm2,Dm3,Ds0,Ds1,Ds2,Ds3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Feb-2024 20:12:10

%E(Z) function of refined Hermite, J=3  K=2 ndiff_mu = 3, ndiff_sigma = 3
t2 = Dm0.^2;
t3 = Ds1.^2;
t4 = 1.0./Ds0.^2;
t5 = sqrt(dt);
t6 = t5.^3;
EZ = [(t4.*(Ds0.*(t5.*(Dm0.*8.0+Dm0.*Dm1.*dt.*4.0+Dm0.*dt.*t3.*4.0)-Ds0.*(t5.*(Ds1.*4.0+Dm0.*Ds2.*dt.*4.0+Dm1.*Ds1.*dt.*4.0)-Ds0.*(Dm2.*t6.*2.0-Ds0.*Ds3.*t6)))-Ds1.*t2.*t6.*4.0))./8.0;(t4.*(dt.*t2.*4.0+Ds0.*(Ds0.*(Dm1.*dt.*4.0+dt.*t3-Ds0.*Ds2.*dt.*2.0+4.0)-Dm0.*Ds1.*dt.*8.0)))./4.0;(Dm0.*t5.*6.0-Ds0.*Ds1.*t5.*3.0)./(Ds0.*2.0)];
end
