function EZ = EZ_m4_s0_3_3(dt,Dm0,Dm1,Dm2,Dm3,Dm4,Ds0)
%EZ_m4_s0_3_3
%    EZ = EZ_m4_s0_3_3(DT,Dm0,Dm1,Dm2,Dm3,Dm4,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Mar-2024 15:45:07

%E(Z) function of refined Hermite, J=3  K=3 ndiff_mu = 4, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm1.^2;
t4 = Ds0.^2;
t5 = dt.^2;
t6 = sqrt(dt);
t7 = t6.^3;
t8 = t6.^5;
EZ = [(Dm0.*t6.*2.4e+1+t4.*(Dm2.*t7.*6.0+Dm0.*Dm3.*t8.*4.0+Dm1.*Dm2.*t8.*6.0+Dm4.*t4.*t8)+Dm0.*Dm1.*t7.*1.2e+1+Dm0.*t3.*t8.*4.0+Dm2.*t2.*t8.*4.0)./(Ds0.*2.4e+1);(dt.*t2.*6.0+t4.*(Dm1.*dt.*6.0+t3.*t5.*4.0+Dm0.*Dm2.*t5.*7.0+Dm3.*t4.*t5.*2.0+6.0)+Dm1.*t2.*t5.*6.0)./(t4.*6.0);(1.0./Ds0.^3.*(Dm0.^3.*t7.*4.0+t4.*(t6.*(Dm0.*1.2e+1+Dm0.*Dm1.*dt.*1.8e+1)+Dm2.*t4.*t7.*7.0)))./4.0];
end
