function EZ = EZ_m3_s0_3_1(dt,Dm0,Dm1,Dm2,Dm3,Ds0)
%EZ_M3_S0_3_1
%    EZ = EZ_M3_S0_3_1(DT,DM0,DM1,DM2,DM3,DS0)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2023 12:23:37

%E(Z) function of refined Hermite, J=3  K=1 ndiff_mu = 3, ndiff_sigma = 0
t2 = Ds0./1.0e+100;
EZ = [(Dm0.*sqrt(dt))./Ds0;t2+1.0;t2];
