function stop = optimdlg(x, optimValues, state)
    global g_ud
    if nargin == 2 %ps or gwo
        state = optimValues;
        optimValues = x;
        x = optimValues.bestx;
    end
    respons = 0.3; %minimum number of seconds between two updates
    if strcmp(state, 'init')
        %there can be several times state=init
        hfig = findobj(0, 'tag', 'optimdlg');
        if isempty(hfig)
            g_ud.stop = false;
            g_ud.tic = tic;
            makefig;
        end
        stop = false;
    else
        stop = g_ud.stop;
        if ~stop
            if toc(g_ud.tic) > respons
                hfig = findobj(0, 'tag', 'optimdlg');
                h = findobj(hfig, 'tag', 'ProgressEdit');
                if isfield(optimValues, 'bestfval')
                    fval = optimValues.bestfval;
                else
                    fval = optimValues.fval;
                end
                s = sprintf('Iteration = %d\nState:%s\nEstimated parameters:\n%s\n Approximate negative sum of loglikelihoods: %g\n', optimValues.iteration, state, num2str(x), fval);
                set(h, 'string', s);
                drawnow;
                g_ud.tic = tic;
            end
        end
    end

end
function fig = makefig

    h0 = figure('Units', 'points',  ...
        'Color', [0.914 0.914 0.914],  ...
        'MenuBar', 'none',  ...
        'Name', 'optimizing...',  ...
        'NumberTitle', 'off',  ...
        'PaperPosition', [18 180 576 432],  ...
        'PaperUnits', 'points',  ...
        'Position', [274 229 270 232],  ...
        'RendererMode', 'manual',  ...
        'Tag', 'optimdlg',  ...
        'ToolBar', 'none',  ...
        'CreateFcn', @(h, evnt)movegui(h, 'center'));

    uicontrol('Parent', h0,  ...
        'Units', 'points',  ...
        'BackgroundColor', [1 1 1],  ...
        'HorizontalAlignment', 'left',  ...
        'ListboxTop', 0,  ...
        'Max', 30,  ...
        'Position', [1 26 266 201],  ...
        'Style', 'edit',  ...
        'Tooltipstring', 'Progress of optimization',  ...
        'Tag', 'ProgressEdit');
    uicontrol('Parent', h0,  ...
        'Units', 'points',  ...
        'ListboxTop', 0,  ...
        'Position', [116 3 55 18],  ...
        'String', 'Stop',  ...
        'Tooltipstring', 'Stop optimization and save the optimal parameter set',  ...
        'Callback', @stopcallback,  ...
        'Tag', 'Pushbutton1');
    drawnow;
    
    if nargout > 0
        fig = h0;
    end
end
function stopcallback(~, ~, ~)
    global g_ud
    disp('Stop pressed')
    g_ud.stop = true;
end
