function ETA = ETA_m2_s2_2_3(dt,Dm0,Dm1,Dm2)
%ETA_M2_S2_2_3
%    ETA = ETA_M2_S2_2_3(DT,DM0,DM1,DM2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-May-2023 16:21:43

t2 = Dm1.^2;
t3 = dt.^2;
t4 = dt.^(3.0./2.0);
t5 = dt.^(5.0./2.0);
ETA = [Dm2.*t4.*(-1.0./4.0)-(Dm0.*(Dm1.*t4.*6.0+t2.*t5.*2.0+sqrt(dt).*1.2e+1+Dm0.*Dm2.*t5.*2.0))./1.2e+1-(Dm1.*Dm2.*t5)./4.0;(Dm1.*dt)./2.0+(t2.*t3)./3.0+(Dm0.*(Dm2.*t3.*7.0+Dm0.*(dt.*6.0+Dm1.*t3.*6.0)))./1.2e+1];
