function ETA = ETA_m3_s0_4_3(dt,Dm0,Dm1,Dm2,Dm3)
%ETA_m3_s0_4_3
%    ETA = ETA_m3_s0_4_3(DT,Dm0,Dm1,Dm2,Dm3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Jan-2024 11:42:19

t2 = Dm1.^2;
t3 = dt.^2;
t4 = dt.^(3.0./2.0);
t5 = dt.^(5.0./2.0);
t6 = Dm2.*t3.*7.0;
t7 = Dm3.*t5.*2.0;
t8 = t2.*t5.*2.0;
ETA = [Dm2.*t4.*(-1.0./4.0)-(Dm0.*(t7+t8+Dm1.*t4.*6.0+sqrt(dt).*1.2e+1+Dm0.*Dm2.*t5.*2.0))./1.2e+1-(Dm1.*Dm2.*t5)./4.0;(Dm1.*dt)./2.0+(Dm3.*t3)./6.0+(t2.*t3)./3.0+(Dm0.*(t6+Dm0.*(dt.*6.0+Dm1.*t3.*6.0)))./1.2e+1;Dm2.*t4.*(-1.0./6.0)+(Dm0.*(t7+t8-Dm1.*t4.*1.2e+1-Dm0.*(Dm0.*t4.*4.0-Dm2.*t5.*2.0)))./2.4e+1+(Dm1.*Dm2.*t5)./8.0;Dm3.*t3.*(-1.0./1.2e+1)-(t2.*t3)./6.0-(Dm0.*(t6+Dm0.*Dm1.*t3.*6.0))./2.4e+1];
end
